import React from "react";

const AudiRS322 = ({audiRS3Img}) => {
    return ( 
        <article className="container car-news-article">
            <h1 className="car-news-article-title pb-4">Audi RS3 2022 "The Green Monster"</h1>
            <b className="car-news-article-desc pb-4">We took the compact sports car Audi RS3 with 400 hp and a dual drive system to the test. It was hot... This green monster we took to the test may seem a bit familiar and innocent, but don't let her fool you. Already from the vehicle's specifications you can see that this is a very fast driving machine with a powerful drive unit, Adjustable sports suspension, and very wide and sticky sports tires. We took the Audi RS3 on a warm weekend for a hot and fun test.</b>
            <div className="container pb-4">
                <div className="row">
                    <img src={audiRS3Img} alt="Audi RS3 2022" className="col-md-12 col-lg-6" />
                    <div className="col-md-12 col-lg-6 car-news-article-img-para">
                        <h2>Audi RS3 design and comfort</h2>
                        <p>Our test car arrived in a phosphorescent green color that looks great but could put you, those around you, and your driver's license at risk. The hot car in a striking color did not stop turning heads, even the heads of law enforcement personnel on the roads. The design is handsome with distinct sporty accents but not in an overly ornate way. In front stands out a huge designed and blackened grille on which the blackened Audi emblem and RS logo are hidden, and large blackened air intakes. The headlights are in the shape of the letter R and in their lower part a nice LED matrix radiating a checkerboard shape, and when the car is opened an RS3 radiates dynamically on the driver's side, letter by letter.</p>
                    </div>
                </div>
            </div>
            <p>The side mirrors and wheel rims are also blacked out and the side skirts have a black panel. In the front wing behind the wheel there is a long ventilation opening. Through the handsome 19-inch rims, large brake discs and large red calipers with RS lettering protrude. At the back, a pair of long taillights with a special LED signature, a large spoiler above the rear window, blacked-out emblems, a black panel with a mesh pattern on the rear bumper, and a large black diffuser with a pair of large oval exhaust openings</p>
            <p>The external dimensions of the Audi A3 place it in the heart of the compact family category. It is 4,389 mm long (50 mm more than the Audi A3 Sportback), 1,984 mm wide (168 mm more than the Audi A3 Sportback), 1,436 mm high (45 mm more than the Audi A3 Sportback), and a wheelbase The wheelbase is 2,631 mm.</p>
            <p>When the door is opened in the dark, a colorful RS logo is projected onto the road. The passenger cabin is modern and handsome, and the seats of the vehicle feature green stitching in the shape of hexagons that match the color of the vehicle. The structure of the dashboard is slightly different from the familiar one. The two air conditioning vents of the driver are located high on the sides of the dashboard. The middle of the dashboard, turned slightly to the driver's side, a 10.1-inch glass screen with a slope and below it a screen panel and the climate control system switches as we like with large and clear switches. To the right of the central screen are long blinds that integrate the pair of air conditioning vents inside them, and below, along the entire length of the dashboard, a brushed aluminum-like panel with a combination of carbon and an ambient lighting strip. The lining materials are soft and very high quality in their upper part. The assembly quality is excellent. At the bottom of the console is a large, bright and efficient open storage compartment with two USB-C sockets. Above it is a row of controls that includes, for example, the switch for selecting the driving modes and canceling the stop-and-go system.</p>
            <p>The electronic gear selector panel in the central console between the driver and passenger is not used for storage solutions and includes an ignition switch and a round control switch for the multimedia system. The armrest is comfortable and below it is a medium-sized square compartment. A large, open storage compartment between the seats can be turned into two cup holders by shifting two original grip rings. The glove box is a reasonable size, sided and lit but not air conditioned. All doors have storage compartments with space for a small bottle.</p>
            <p>The 12.3-inch digital dashboard is excellent, controlled via convenient controls on the steering wheel and allows for a variety of display options to choose from. The steering wheel is truncated, covered with perforated leather that is comfortable to hold. In the center is a round navel with the brand logo in an aluminum-like finish and below it a colorful RS logo. Switches on both sides of the steering wheel allow control of the vehicle's systems, and a pair of aluminum pedals behind the steering wheel allow manual control of the gear shift.</p>
            <p>As mentioned, the great sports seats include a lot of green stitching and are very comfortable to sit on. The side support is great for both the back and legs. The seats are electrically adjustable, including the height and depth of the back support. You can also extend the base of the seat manually and reach a comfortable and efficient driving position together with manual adjustment of the height and depth of the steering wheel.</p>
            <p>The seats are low as befits a sports car but can be raised if you wish. The front door key is generous but the side support in the seats is thick and will make it a little difficult to get into the front seats. The window threshold is high due to the low seats, and with the exception of slightly small side mirrors, the field of vision to the front and sides is good. Rear visibility is also good and front and rear proximity sensors are also installed, as well as a high-quality rear camera. The internal mirror is large and beautiful without a frame and includes automatic dimming. The sun awnings are large and comfortable with lighting and a mirror. The panoramic sunroof in front lets a lot of light into the car when it is opened.</p>
            <p>Excellent human engineering. The presence of the useful switches is very correct and does not require wandering through different screens. Despite the presence of the switches, the manner in which they are arranged and positioned maintains the clean and modern appearance, and proves that it is possible to enjoy all worlds (to the attention of the hundreds of car designers who sacrifice usability to the point of sacrificing design). Above the controls of the climate control system is a small screen that displays exactly above each switch its status, making it very easy to use even at night.</p>
            <p>The center screen and dashboard screen are high resolution and contrast, and even though the center screen is slanted and exposed to the sun, it looks great even on a sunny day. The different display screens are beautiful and intuitive and you can choose different display styles on the dashboard. The multimedia system supports Apple CarPlay and Android Auto, and the excellent 3D audio system from Bang & Olufsen with a power of 680w includes 15 speakers that offer great audio quality.</p>
            <p>The back seats will be very comfortable for two adult passengers, but the legroom is limited and consideration is required from the front passengers. Two passengers in the back will also be able to enjoy a wide and comfortable armrest with 2 cup holders. An additional passenger in the middle seat will be less comfortable due to a hardened seat and a large step. At the back there are air conditioning vents and a separate climate control area with the possibility of temperature adjustment. The ceiling of the vehicle is black and includes four LED type lighting fixtures for all passengers with dimming option.</p>
            <p>The trunk has a reasonable volume of 380 liters and features a low loading threshold, an accessible key, and practical solutions such as hooks for hanging bags. Each of the three back seats in the back has a back that can be quickly and conveniently folded, allowing for a large and almost completely flat cargo area. Long objects can be transported even with 4 passengers in the car by simply folding the back of the central seat. Under the trunk floor is a tire repair kit. If you have an ATV or jet ski, you should know that the Audi RS3 must not be fitted with a tow bar.</p>
            <p>We start the trip in the city with a combination of Comfort driving mode. In this situation we seem to be driving a regular German compact family car and not a sporty one. The suspension's damping capacity is good and road fragments and deceleration strips are well restrained despite the low section of the tires. We were surprised to find that a combination of dynamic driving mode also leaves the vehicle quite comfortable in the city and did not cause shocks to the occupants of the car despite the stiffening of the suspension.</p>
            <p className="pb-5">Even outside the city the ride quality is very good. The gear changes are performed smoothly both in strong accelerations and in decelerations. The windshield is acoustic and the noise isolation is very good, including road noise isolation despite the wide, low-cut tires. The sound of the beefy engine can be heard with pleasure during hard effort.</p>
            <h2>The Performance Of The Audi RS3</h2>
            <p>Audi RS3 is equipped with a 5-cylinder gasoline turbo engine with a volume of 2,480 cc with a maximum power of 400 hp obtained in the range of 5,600-7,000 rpm, and a maximum torque of 51.0 kgm obtained in the range of 2,250-5,600 rpm. The engine is mated to a 7-speed dual-clutch robotic gearbox and a quattro AWD system. The shock absorbers are adaptive and can be adjusted individually or according to the driving conditions. The shock absorbers are adaptive and can be adjusted individually or according to the driving conditions.</p>
            <p>The braking system includes calipers with 6 pistons and ventilated discs measuring 375 x 36 mm in front and 310 x 22 mm in the rear. The semi-slicks sports tires are particularly sticky Michelin Pilot Sport Cup2. Due to the AWD system embedded in a front-wheel-drive platform, Audi chose wider tires and a lower cut in the front.The tire sizes are 265/30R19 in the front and 245/35R19 in the back.</p>
            <p>The driving mode selector allows you to choose from no less than 7 different modes. an efficiency mode for a comfortable and economical ride, a comfort mode for a comfortable ride, a little more dynamic and less economical, an automatic mode for a comfortable ride that adapts to the road conditions and the driver's requirements, and a dynamic mode that stiffens the steering wheel and suspension and sharpens the engine's responses and the gearbox while maintaining a high rpm and a power band in an available state at the expense of higher fuel consumption and pollution. In addition, 3 more RS sport modes are offered. Personal RS mode (RS Individual) for personal selection of each drive component, RS Performance mode intended for the race track, and Rear Drive mode (RS Torque Rear) intended for drifts and not recommended on public roads.</p>
            <p>In personal RS mode you can, as mentioned, control all the features of the adjustable drive components. For the torque distribution component, you can set values ​​of Comfortable for dynamic power distribution between the axles that will result in maximum comfort, Balanced for equal power distribution between the axles, and Dynamic for dynamic power distribution between the axles that will result in maximum performance.</p>
            <p>Drive system components can be set to Efficient for fuel economy, Balanced and Dynamic for maximum performance. Dynamic mode keeps the box in low gear and the engine at high rpm, which sometimes requires intervention and manual setting of the gear with the help of the small pedals behind the steering wheel. For the Suspension and Steering components, you can set values ​​of Comfortable for maximum softness, Balanced, and Dynamic for maximum stiffness.</p>
            <p>Engine sound can be set to Subdued, Automatic and Pronounced. The RS package has a unique RS sports exhaust system, but unfortunately the sound of the exhaust system is not sufficiently invested and even in "Pronounced" mode, the sound of the engine is not appropriate for a powerful car with 400 hp. We really missed beefy, crackling engine growls. At that price we would like everyone to hear who has the meanest car in the neighborhood.</p>
            <p>The stability control system (ESC) component can be set to On and Dynamic values ​​for a controlled and controlled release of the system for interesting drifting which is not recommended on public roads. The stability control can also be quickly canceled by a unique switch on the center console.</p>
            <p>A ratio of 1 hp per 3.9 kg, a fast 7-speed dual-clutch robotic transmission, a launch control system, acceleration from zero to 100 km/h in 3.8 seconds, a AWD system, adjustable sports suspension, and wide, sticky low-cut tires, look great On paper, it is very important how they all translate to the dynamic ability of the Audi RS3.</p>
            <p>With the help of the launch control system and the acceleration measurement system installed in the vehicle, we were able to measure and display on the dashboard 4.1 seconds in acceleration from zero to 100 km/h, very close to the official acceleration figure of 3.8 seconds and very impressive for a compact and useful family car.</p>
            <p>With the exception of a noticeable turbo lag at the beginning of acceleration, the engine and gearbox play together excellently as we are used to in the Volkswagen concern. The gear changes are fast and smooth even during fast accelerations and strong braking. The excellent sports tires and the AWD system ensure that the power is transferred to the road in an optimal way without power losses, and the performance is indeed dizzying.</p>
            <p>Together with the adjustable sports suspension and integration into the RS Performance driving mode, it is possible to attack winding roads at high speed with small roll angles and excellent controllability of the fighting machine. The steering wheel has 3 resistance modes, and in dynamic mode it is tough enough, communicates well, fast and accurate. The wonderful suspensions provide an incomprehensible charm of excellent braking ability and not bad comfort even on bumpy roads.</p>
            <p>After a few curves in which we learned about the car's behavior, the grip of the tires, the braking ability and the way the power drops to the road, we were able to attack bends at higher and higher speeds with less worries and much more smiles and enjoyment, without really tickling the car's limits on a dry road. Brakes are very strong and did not get tired even after prolonged effort.</p>
            <p className="pb-5">To summarize the performance chapter, it can be said that the Audi RS3 is an excellent, powerful and mature sports performance machine. In our opinion, with the combination of a full or partial hybrid system, it would have been possible to compensate for the turbo lag and contribute to better fuel consumption.</p>
            <h2>Audi RS3 Fuel Consumption</h2>
            <p>On our test drive which included decent presses of the accelerator pedal, we achieved a fuel consumption of 6.9 km per liter which matched the long-term fuel consumption of the test vehicle. The official fuel consumption figure is 11.0 km per liter and we have no doubt that it is possible to get very close to such fuel consumption in a calm and boring drive that does not suit the vehicle's purpose.</p>
            <p className="pb-5">The fuel tank with a volume of 55 liters is not big enough for our taste and will provide a driving range of only about 380 km between refuelings. The Audi RS3 is equipped with a stop-go system which should contribute very little to fuel consumption, especially in the Israeli summer where it is customary to deactivate it at the beginning of each trip due to turning off the air conditioner in idle mode. As we mentioned in the performance section, the integration of a hybrid system would have contributed to improving fuel consumption and driving range between refuelings. The degree of air pollution is 15 out of 15 according to the Israeli Ministry of Transport.</p>
            <h2>Audi RS3 Reliability And Maintenance Costs</h2>
            <p>Audi vehicles do not receive a high score in the reliability section. In a satisfaction survey conducted by the Consumer Reports organization in the USA in 2022, Audi came in 14th place out of 26 manufacturers. In a survey by the J.D. Power, which is held in the USA and measures the amount of breakdowns per 100 vehicles, Audi came 20th out of 33 manufacturers. In a similar survey conducted by the organization in Germany, Audi received a less than flattering score and was ranked 20th out of 22 manufacturers.</p>
            <p>Audi models are marketed in Israel with a full manufacturer's warranty for three years with no km limit. Treatments should be performed once a year or every 15,000 km. The prices of the treatments and spare parts are not published on the Internet and we were not able to receive them from the importer Champion Motors.</p>
            <p className="pb-5">The cost of comprehensive insurance for every driver aged 25 and over with 7 years of driving experience without claims or license revocations is about 22,000₪, and the cost of mandatory insurance is about 2,000₪.</p>
            <h2>The Safety Of Audi RS3</h2>
            <p>The Audi A3, on which the Audi RS3 is based, was tested in the safety tests of the Euro NCAP organization in 2020 and received a maximum score of five stars with scores of 89% in the protection of adults, 81% in the protection of children, 68% in the protection of pedestrians, and 73% for the safety systems . The level of safety equipment is 6 out of 8 according to the Israeli Ministry of Transport.</p>
            <p className="pb-5">The safety equipment includes, among other things, 6 airbags, tire pressure sensors, peripheral parking sensors, reversing camera, automatic control of high beams, parking assistance system, LED fog lights, full LED lighting, light and rain sensors, side mirrors and interior mirror with automatic dimming to prevent glare, lane departure warning with active correction, blind spot warning, pedestrian and vehicle collision warning, autonomous braking with pedestrian and cyclist detection, adaptive cruise control including full stop and jump from a standstill, and driver fatigue warning.</p>
            <h2>Value for money and Audi RS3 summary</h2>
            <p>Audi RS3 is marketed in Israel at a price of 472,500₪, and the RS accessory package is offered for an additional 19,500₪. The equipment specification of the Audi RS3 includes, among other things, a 12.3-inch digital dashboard, a multimedia system with a 10.1-inch touch screen, Bluetooth connectivity, support for Apple CarPlay and Android Auto interfaces with cable connection, 180W audio system with 10 speakers, full LED lighting, smart key, electric panoramic sun window, RS logo projection when opening the front doors, ambient lighting with a variety of colors to choose from, a digital climate control system with rear air conditioning vents and three control zones, and leather-upholstered seats.</p>
            <p>The RS equipment package adds to the list a 3D audio system from Bang & Olufsen with a power of 680W with 15 speakers, LED matrix lighting with dynamic signaling and a unique light signature, an RS sports exhaust system, and an adaptive sports suspension system.</p>
            <p>The drive system is excellent and includes a multitude of adjustments for every situation. The high power, the dual drive system, the adjustable sports suspension, and the excellent tires provide dizzying dynamic performance. Add to that a launch control system, rear wheel drive mode and wide, sticky tires and you got an excellent track car as well as a machine for acceleration and drifting.</p>
            <p>Although the price of the Audi RS3 is lower than the price of the Mercedes A45 AMG, which offers similar data, and it has no other similar competitors, the price of half a million for a compact family car, however hot, seems very high to us. In our opinion, a more attractive price could have made the car more popular and also more profitable to manufacture.</p>
            <p className="pb-5">The Audi RS3 is a real sports car with a very high dynamic capability without sacrificing too much comfort and high usability in the everyday life of the family. Audi RS3 will be comfortable and useful for a family in the middle of the week, and at the weekend it will give love, warmth and a lot of pleasure to its owner.</p>
            <p><b>POSTED ON <a href="https://www.gear.co.il/%D7%9B%D7%AA%D7%91%D7%AA-%D7%A8%D7%9B%D7%91/2022-08-22-N01-%D7%9E%D7%91%D7%97%D7%9F-%D7%93%D7%A8%D7%9B%D7%99%D7%9D-%D7%90%D7%90%D7%95%D7%93%D7%99-RS3-%D7%A1%D7%A4%D7%95%D7%A8%D7%98%D7%91%D7%A7" className="car-news-article-credits">AUGUST 22, 2022</a> BY <a href="https://www.gear.co.il/%D7%9B%D7%AA%D7%91%D7%AA-%D7%A8%D7%9B%D7%91/2022-08-22-N01-%D7%9E%D7%91%D7%97%D7%9F-%D7%93%D7%A8%D7%9B%D7%99%D7%9D-%D7%90%D7%90%D7%95%D7%93%D7%99-RS3-%D7%A1%D7%A4%D7%95%D7%A8%D7%98%D7%91%D7%A7" className="car-news-article-credits">KOBI ZVILI</a></b></p>
        </article>
     );
}
 
export default AudiRS322;