import React from "react";

const CarsNotComingIsr = ({ carsDelayImg }) => {
    return (
        <article className="container car-news-article">
            <h1 className="car-news-article-title pb-4">Cars Are Delayed On The Way To Israel</h1>
            <b className="car-news-article-desc pb-5">As planned, Israel was supposed to meet the electric cars of Mazda and Renault, a 7 seater Nissan and the new family car from Peugeot. but it didn't happend.</b>
            <div className="container pb-4">
                <div className="row">
                    <img src={carsDelayImg} alt="cars not coming to israel image" className="col-md-12 col-lg-6" />
                    <div className="col-md-12 col-lg-6 car-news-article-img-para">
                        <h2>What Happened?</h2>
                        <p>The chips and raw materials crisis affecting the automobile industry is creating significant delays in the arrival of new vehicles to Israel.Consumers are exposed to this phenomenon mainly when it comes to the waiting times for the delivery of vehicles,who arrive more than once a year or more; We have already come across importers who have completely stopped orders for certain models due to the lengthening of the order list, and also in leasing customers who have been waiting for a popular family car for a year and still don't see the car on the horizon.</p>
                        <p>But this phenomenon has additional consequences. Every year the manufacturers reveal new models and the importers update the public regarding the estimated arrival dates in Israel.</p>
                    </div>
                </div>
            </div>
            <p>surely, the guaranteed deadlines are never accurate, exception of a few months are commonplace, But in the last year the phenomenon intensified to dimensions we have not yet encountered.</p>
            <p className="pb-5">At the beginning of this year, the arrival of 76 new car models to Israel was promised; By the end of August, only 35 of them had landed here. And what about the remaining 41? less than 10 of them will definitely arrive by the end of this year, The rest will be delayed until an unknown date. The list of outstanding delays is in front of you.</p>
            <h2>Which Manufactors?</h2>
            <p className="pb-5"><b>Mazda - </b>already last year, the importer promised to land the MX30 electric SUV vehicle in Israel, but with a stated range of only 200 kilometers and a high price tag (which reached 200,000₪ at the parallel importers) its chances of success seemed low anyway. The large Mazda CX-60 SUV vehicle looks like a product that would be more suitable for the Israeli market, and was supposed to arrive here at the end of this year - but its launch was postponed to the beginning of 2023.</p>
            <p className="pb-5"><b>Ford - </b>With the same importer, they aimed already last year to start marketing the new generation Ford Kuga, As well as the electric Mustang Mach E - of which over 100 units have already been sold this year in the parallel and personal import channels. Both are still pending.</p>
            <p className="pb-5"><b>Renault - </b>Many times after the arrival of the hybrid Clio fell off the daily routine, The electric Megane E Tech is also getting further and further away from the roads of our country. Renault's electric family car offers a SUV-like design and slightly smaller dimensions than the Hyundai Ioniq 5 - which made us dream of more attractive pricing. Right now it seems far away.</p>
            <p className="pb-5"><b>Nissan - </b>Renault's sister company will also try to launch the electric SUV vehicle Nissan Ariya this year, but the noticeable delayer here is actually the X-Trail. The new generation of the 7-seater car, almost twin brother to the Mitsubishi Outlander, it was already revealed two years ago and was supposed to arrive this year. But it won't come.</p>
            <p className="pb-5"><b>Dacia - </b>The low-cost brand of the Craso importer planned to launch the Dacia Spring in the middle of this year, the small electric car that was supposed to be the cheapest of its kind in Israel. In the meantime individual units arrived in parallel imports at relatively high prices, maybe towards the end of the year we will see it here also in the regular import. Those who are not expected to arrive this year are Sandro and Logan, which were supposed to be here on last year.</p>
            <p className="pb-5"><b>Peugeot - </b>The family 308 car was supposed to land with us several months ago, but will arrive only next year. Those who have trouble waiting will be able to order her almost-twin sister in the coming weeks, the new Opel Astra.</p>
            <p className="pb-5"><b>MG - </b>The right to be the first in the Chinese brand revolution in Israel belongs to MG, which has been selling Chinese-made vehicles here for over a decade. At the beginning of this year the importer started selling the electric an updated version of the ZS, but as of today the vehicles have not yet arrived in Israel; The family MG5 and the Marvel R SUV were also due to arrive early this year, but at the moment the estimates speak of a launch only at the beginning of next year.</p>
            <p className="pb-5"><b>Suzuki - </b>at the end of last year, two important models called Suzuki Swayze and Suzuki Across were supposed to land here, which are actually identical twins of the Toyota Corolla Station and Toyota Rav 4 Plug-in. The two were born out of the manufacturer's need to lower the emission averages in Europe, and for exactly the same reason they also stayed on the old continent.</p>
            <p className="pb-5"><b>Aiways - </b>The young electric brand from China started here with a single SUV vehicle called the U5, like his competitors he managed to accumulate a rather long list of orders. At the beginning of the year another model in the configuration of a SUV coupe named U6 was also supposed to land here, but at the moment it seems that it will arrive only next year.</p>
            <p className="pb-5"><b>Skywell - </b>At the beginning of this year the electric manufacturer promised to add to the local supply a new small SUV vehicle and another larger model with 7 seats. So far these two have not yet been revealed to the public, and therefore your arrival in Israel is not yet in sight.</p>
            <p className="pb-5"><b>Hyundai - </b>The Ionic 5 electric has accumulated a long waiting list in the past months, but part of the burden was soon to be transferred to the shoulders of the Ionic 6, an electric sedan that was recently unveiled as a competitor to the Tesla Model 3. In the meantime the estimated marketing date has been postponed from the last quarter of 2022 to the second quarter of 2023.</p>
            <p className="pb-5"><b>Kia - </b>This year we did have the launch of the Sportage, one of the most significant models of the manufacturer and of the Israeli market in general, and the electric EV6 may also land here before the end of the year. But the popular little brother, the new Kia Niro, delayed for the time being and will probably arrive only next year. In its place we will soon meet here in the Kia Niro Plus - a raised and enlarged version of the outgoing Niro, which will be marketed with all known drive units: hybrid, plug-in hybrid and electric.</p>
            <p className="pb-5"><b>Mitsubishi - </b>To the new generation of the Outlander, which arrived in Israel about a year ago, a rechargeable hybrid version was also supposed to join soon - unlike in the past, already includes an option for 7 seats. Meanwhile the rechargeable Outlander is delayed, but in its place a plug-in hybrid version for the smaller Eclipse Cross is expected to arrive soon.</p>
            <p className="pb-5"><b>Ssangyong - </b>The Korando recreational vehicle was not successful in the gasoline and diesel versions, but the electric version might be the one that changes things around. The importer hoped it would arrive this year, but the launch will be postponed until next year.</p>
            <p className="pb-5"><b>Chevrolet - </b>In recent years, the importer promises almost every year to finally start regular marketing of the sporty Corvette, but it is shy to arrive. In the meantime, hundreds of Corvettes with parallel and personal imports are hitting the roads, and although this year too we heard a promise of an approaching start of marketing - we will have to continue to wait.</p>
            <p><b>POSTED ON <a href="https://www.icar.co.il/%D7%97%D7%93%D7%A9%D7%95%D7%AA_%D7%A8%D7%9B%D7%91/%D7%9E%D7%A6%D7%98%D7%A2%D7%A8%D7%99%D7%9D,_%D7%94%D7%94%D7%A9%D7%A7%D7%94_%D7%A0%D7%93%D7%97%D7%99%D7%AA:_%D7%94%D7%A8%D7%9B%D7%91%D7%99%D7%9D_%D7%A9%D7%9E%D7%AA%D7%A2%D7%9B%D7%91%D7%99%D7%9D_%D7%91%D7%93%D7%A8%D7%9A_%D7%9C%D7%99%D7%A9%D7%A8%D7%90%D7%9C/" className="car-news-article-credits">AUGUST 30, 2022</a> BY <a href="https://www.icar.co.il/%D7%97%D7%93%D7%A9%D7%95%D7%AA_%D7%A8%D7%9B%D7%91/%D7%9E%D7%A6%D7%98%D7%A2%D7%A8%D7%99%D7%9D,_%D7%94%D7%94%D7%A9%D7%A7%D7%94_%D7%A0%D7%93%D7%97%D7%99%D7%AA:_%D7%94%D7%A8%D7%9B%D7%91%D7%99%D7%9D_%D7%A9%D7%9E%D7%AA%D7%A2%D7%9B%D7%91%D7%99%D7%9D_%D7%91%D7%93%D7%A8%D7%9A_%D7%9C%D7%99%D7%A9%D7%A8%D7%90%D7%9C/" className="car-news-article-credits">NOAM RYAN</a></b></p>
        </article>
    );
}

export default CarsNotComingIsr;